// <auto-generated />
using System;
using HotelBooking.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("DiscountLimit")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountLimit = 0f,
                            Email = "Admin@HMS.com",
                            PasswordHash = "5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8",
                            PhoneNumber = "01021565688",
                            Role = "Admin",
                            UserName = "Admin",
                            createdAt = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "Server",
                            updatedAt = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedBy = "Server"
                        });
                });

            modelBuilder.Entity("HotelBooking.Models.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("configurations");
                });

            modelBuilder.Entity("HotelBooking.Models.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationAttachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("bit");

                    b.Property<string>("MarriageCertificateAttachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriageCertificateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriedToCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Age = 0,
                            BirthDate = new DateOnly(1995, 3, 12),
                            Email = "john.ahmady@gmail.com",
                            IdentificationAttachment = "id1.jpg",
                            IdentificationNumber = "30105060784512",
                            IdentificationType = "National ID",
                            IsMarried = false,
                            Name = "John El Ahmady",
                            Nationality = "Egyptian",
                            PhoneNumber = "01022289755",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Registered",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Egypt",
                            Age = 0,
                            BirthDate = new DateOnly(1997, 7, 21),
                            Email = "sara.mahmoud@gmail.com",
                            IdentificationAttachment = "passport2.jpg",
                            IdentificationNumber = "A23456789",
                            IdentificationType = "Passport",
                            IsMarried = false,
                            Name = "Sara Mahmoud",
                            Nationality = "Egyptian",
                            PhoneNumber = "01144556677",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Registered",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "New York, USA",
                            Age = 0,
                            BirthDate = new DateOnly(1990, 11, 4),
                            Email = "m.smith@example.com",
                            IdentificationAttachment = "passport3.png",
                            IdentificationNumber = "X98765432",
                            IdentificationType = "Passport",
                            IsMarried = false,
                            Name = "Michael Smith",
                            Nationality = "American",
                            PhoneNumber = "+1-202-555-0188",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Registered",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alexandria, Egypt",
                            Age = 0,
                            BirthDate = new DateOnly(1998, 1, 1),
                            Email = "fatima.ali@example.com",
                            IdentificationAttachment = "id4.png",
                            IdentificationNumber = "29801011234567",
                            IdentificationType = "National ID",
                            IsMarried = false,
                            Name = "Fatima Ali",
                            Nationality = "Egyptian",
                            PhoneNumber = "01234567890",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Registered",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "London, UK",
                            Age = 0,
                            BirthDate = new DateOnly(1988, 5, 30),
                            Email = "david.johnson@example.co.uk",
                            IdentificationAttachment = "dl5.pdf",
                            IdentificationNumber = "DLUK998877",
                            IdentificationType = "Driver License",
                            IsMarried = false,
                            Name = "David Johnson",
                            Nationality = "British",
                            PhoneNumber = "+44-7700-900123",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Registered",
                            updatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotelBooking.Models.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("badgeBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("badgeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 1000f,
                            Type = "Single",
                            badgeBg = "",
                            badgeText = "",
                            createdAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "Server",
                            updatedAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedBy = "Server"
                        },
                        new
                        {
                            Id = 2,
                            Price = 1500f,
                            Type = "Double",
                            badgeBg = "",
                            badgeText = "",
                            createdAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "Server",
                            updatedAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedBy = "Server"
                        },
                        new
                        {
                            Id = 3,
                            Price = 3000f,
                            Type = "Suite",
                            badgeBg = "",
                            badgeText = "",
                            createdAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = "Server",
                            updatedAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedBy = "Server"
                        });
                });

            modelBuilder.Entity("HotelBooking.Models.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<float>("Dues")
                        .HasColumnType("real");

                    b.Property<int>("NumberOfAdults")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfExtraBeds")
                        .HasColumnType("int");

                    b.Property<float>("Paid")
                        .HasColumnType("real");

                    b.Property<string>("ProofOfPayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Discount = 0f,
                            Dues = 0f,
                            NumberOfAdults = 1,
                            NumberOfChildren = 0,
                            NumberOfExtraBeds = 0,
                            Paid = 200f,
                            ProofOfPayment = "",
                            RoomId = 1,
                            RoomType = "Single",
                            Status = "Reserved",
                            createdAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CheckInDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Discount = 0f,
                            Dues = 0f,
                            NumberOfAdults = 1,
                            NumberOfChildren = 1,
                            NumberOfExtraBeds = 0,
                            Paid = 150f,
                            ProofOfPayment = "",
                            RoomId = 1,
                            RoomType = "Single",
                            Status = "Reserved",
                            createdAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CheckInDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Discount = 10f,
                            Dues = 50f,
                            NumberOfAdults = 2,
                            NumberOfChildren = 1,
                            NumberOfExtraBeds = 1,
                            Paid = 300f,
                            ProofOfPayment = "",
                            RoomId = 101,
                            RoomType = "Double",
                            Status = "Reserved",
                            createdAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CheckInDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            Discount = 5f,
                            Dues = 200f,
                            NumberOfAdults = 4,
                            NumberOfChildren = 2,
                            NumberOfExtraBeds = 2,
                            Paid = 1000f,
                            ProofOfPayment = "",
                            RoomId = 201,
                            RoomType = "Suite",
                            Status = "Reserved",
                            createdAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotelBooking.Models.RoomModels.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            Floor = 1,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S001",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1,
                            Floor = 1,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S002",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1,
                            Floor = 1,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S003",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1,
                            Floor = 1,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S004",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 1,
                            Floor = 1,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S005",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 1,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S006",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 1,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S007",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 1,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S008",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 1,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S009",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 1,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "S010",
                            RoomType = "Single",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 101,
                            Capacity = 2,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D001",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 102,
                            Capacity = 2,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D002",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 103,
                            Capacity = 2,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D003",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 104,
                            Capacity = 2,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D004",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 105,
                            Capacity = 2,
                            Floor = 2,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D005",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 106,
                            Capacity = 2,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D006",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 107,
                            Capacity = 2,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D007",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 108,
                            Capacity = 2,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D008",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 109,
                            Capacity = 2,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D009",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 110,
                            Capacity = 2,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "D010",
                            RoomType = "Double",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201,
                            Capacity = 4,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU001",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202,
                            Capacity = 4,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU002",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 203,
                            Capacity = 4,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU003",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 204,
                            Capacity = 4,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU004",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 205,
                            Capacity = 4,
                            Floor = 3,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU005",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 206,
                            Capacity = 4,
                            Floor = 4,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU006",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 207,
                            Capacity = 4,
                            Floor = 4,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU007",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 208,
                            Capacity = 4,
                            Floor = 4,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU008",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 209,
                            Capacity = 4,
                            Floor = 4,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU009",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 210,
                            Capacity = 4,
                            Floor = 4,
                            Images = "",
                            Price = 0f,
                            RoomNumber = "SU010",
                            RoomType = "Suite",
                            createdAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
