// <auto-generated />
using HotelBooking.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250817073655_AddNationalitlyToDB")]
    partial class AddNationalitlyToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Models.Customer", b =>
                {
                    b.Property<int>("Cust_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cust_ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_Image_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mariage_cert_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Marriage_status")
                        .HasColumnType("bit");

                    b.Property<string>("National_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone_Number")
                        .HasColumnType("int");

                    b.HasKey("Cust_ID");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Cust_ID = 1,
                            Email = "john@gmail.com",
                            Full_Name = "John El Ahmady",
                            ID_Image_URL = "",
                            Mariage_cert_URL = "",
                            Marriage_status = false,
                            National_ID = "101050607845",
                            Nationality = "Egypt",
                            Phone_Number = 1022289755
                        },
                        new
                        {
                            Cust_ID = 2,
                            Email = "sarah.mostafa@gmail.com",
                            Full_Name = "Sarah Mostafa",
                            ID_Image_URL = "",
                            Mariage_cert_URL = "",
                            Marriage_status = true,
                            National_ID = "298030512345",
                            Nationality = "Egypt",
                            Phone_Number = 1015673248
                        },
                        new
                        {
                            Cust_ID = 3,
                            Email = "omar.khaled@yahoo.com",
                            Full_Name = "Omar Khaled",
                            ID_Image_URL = "",
                            Mariage_cert_URL = "",
                            Marriage_status = false,
                            National_ID = "300070923456",
                            Nationality = "Brazil",
                            Phone_Number = 1098765432
                        },
                        new
                        {
                            Cust_ID = 4,
                            Email = "nour.hassan@hotmail.com",
                            Full_Name = "Nour El Din Hassan",
                            ID_Image_URL = "",
                            Mariage_cert_URL = "",
                            Marriage_status = true,
                            National_ID = "295112245678",
                            Nationality = "Brazil",
                            Phone_Number = 1122334455
                        },
                        new
                        {
                            Cust_ID = 5,
                            Email = "mona.adel@gmail.com",
                            Full_Name = "Mona Adel",
                            ID_Image_URL = "",
                            Mariage_cert_URL = "",
                            Marriage_status = false,
                            National_ID = "301022334567",
                            Nationality = "Brazil",
                            Phone_Number = 1033445566
                        },
                        new
                        {
                            Cust_ID = 6,
                            Email = "ahmed.samir@outlook.com",
                            Full_Name = "Ahmed Samir",
                            ID_Image_URL = "",
                            Mariage_cert_URL = "",
                            Marriage_status = true,
                            National_ID = "299041556789",
                            Nationality = "Brazil",
                            Phone_Number = 1255667788
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
